databases:
  - name: DebtManager
    databaseName: debtmanager
    user: debtmanager_user

services:
  - type: web
    name: DebtManager
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: debtmanager
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false