local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

# Remember not to checkin your GCS keyfile to a repository
google:
  service: GCS
  project: debtmanager-400315
  credentials: <%= Rails.root.join("gcs.keyfile") %>
  bucket: topacash<%= Rails.env %>
